//! Workspace-hack crate for unified dependency features.
//!
//! This crate is auto-generated by cargo-hakari. It ensures that all workspace
//! members compile dependencies with consistent feature sets, reducing duplicate
//! compilations and improving build times.
//!
//! **DO NOT EDIT** - Run `cargo hakari generate` to regenerate.
//!
//! See <https://docs.rs/cargo-hakari> for more information.

#![allow(dead_code)]
#![allow(unused_imports)]
